server:
  error:
    include-message: always
spring:
  application:
    name: social-media
  profiles:
    active: loc
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml

jwt:
  token:
    secret: ZG9uaWtzZWNyZXQ=
    validity: 86400000

springdoc:
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    display-request-duration: true
    operations-sorter: method
    path: /docs
    default-models-expand-depth: -1

services:
  s3:
    endpoint: http://localhost:9000
    minio-host: https://localhost:9000
    access-key: user
    secret-key: password
    bucket-name: posts
    region: us-east-1
file:
  upload-dir: D:\\uploads